import numpy as np

def simulate_gbm(
    s0: float,
    mu: float,
    sigma: float,
    T: float,
    n_steps: int,
    seed: int | None = None,
) -> np.ndarray:
    """Simulates a single geometric Brownian motion (GBM) price path.

    The path is generated by discretising the stochastic differential equation
    dS = mu * S * dt + sigma * S * dW using the exact solution for GBM, which
    avoids discretisation bias in the drift term:

        S(t + dt) = S(t) * exp((mu - 0.5 * sigma^2) * dt + sigma * sqrt(dt) * Z)

    where Z is a standard normal random variable.

    Args:
        s0: Initial asset price at time 0. Must be positive.
        mu: Drift coefficient (annualised expected rate of return).
        sigma: Volatility coefficient (annualised standard deviation of
            returns). Must be non-negative.
        T: Total time horizon over which to simulate.
        n_steps: Number of discrete time steps to divide the horizon into. Must
            be a positive integer.
        seed: Optional seed for the random number generator, used to make the
            simulation reproducible. If None, a non-deterministic seed is used.

    Returns:
        A 1-D numpy array of length n_steps + 1 containing the simulated price
        path, where the element at index 0 is s0 and the element at index i is
        the simulated price at time i * (T/n_steps).
    """
    rng = np.random.default_rng(seed)
    dt = T / n_steps

    prices = np.zeros(n_steps + 1)
    prices[0] = s0

    for i in range(1, n_steps + 1):
        z = rng.standard_normal()
        prices[i] = prices[i - 1] * np.exp(
            (mu - 0.5 * sigma**2) * dt + sigma * np.sqrt(dt) * z
        )

    return prices