"""GBM price simulation and Poisson-intensity order arrival dynamics."""

import numpy as np

from src.config import SimulationConfig

def simulate_gbm(
    config: SimulationConfig,
    seed: int | None = None,
) -> np.ndarray:
    """Simulates a single geometric Brownian motion (GBM) price path.

    The path is generated by discretising the stochastic differential equation
    dS = mu * S * dt + sigma * S * dW using the exact solution for GBM, which
    avoids discretisation bias in the drift term:

        S(t + dt) = S(t) * exp((mu - 0.5 * sigma^2) * dt + sigma * sqrt(dt) * Z)

    where Z is a standard normal random variable.

    Args:
        config: Simulation parameters (s0, mu, sigma, T, n_steps).
        seed: Optional seed for the random number generator, used to make the
            simulation reproducible. If None, a non-deterministic seed is used.

    Returns:
        A 1-D numpy array of length n_steps + 1 containing the simulated price
        path, where the element at index 0 is s0 and the element at index i is
        the simulated price at time i * (T/n_steps).
    """
    rng = np.random.default_rng(seed)
    dt = config.T / config.n_steps

    prices = np.zeros(config.n_steps + 1)
    prices[0] = config.s0

    z = rng.standard_normal(config.n_steps)
    drift = (config.mu - 0.5 * config.sigma**2) * dt
    diffusion = config.sigma * np.sqrt(dt) * z
    returns = np.exp(drift + diffusion)
    prices[1:] = prices[0] * np.cumprod(returns)

    return prices


def fill_intensity(
    delta: float,
    A: float,
    k: float,
) -> float:
    """Computes the order arrival intensity at a given distance from mid.

    Implements lambda(delta) = A * exp(-k * delta), the fill-intensity model
    from Avellaneda-Stoikov (2008): intensity decays exponentially as a quote
    moves further from the mid-price.

    Args:
        delta: Distance of the quote from the mid-price. Must be non-negative.
        A: Base arrival intensity at delta = 0.
        k: Decay rate controlling how quickly intensity falls off with distance
            from mid.

    Returns:
        The order arrival intensity (lambda) at the given delta.
    """
    intensity = A * np.exp(-k * delta)

    return intensity


def order_arrives(
    delta: float,
    A: float,
    k: float,
    dt: float,
    rng: np.random.Generator,
) -> bool:
    """Decides whether a market order arrives and hits a quote

    Computes the fill probability as intensity * dt, then draws one uniform
    random number from rng and checks whether it falls below that
    probability.

    Args:
        delta: Distance of the quote from the mid-price. Must be non-negative.
        A: Base arrival intensity at delta = 0.
        k: Decay rate controlling how quickly intensity falls off with distance
            from mid.
        dt: Length of the discrete time slice being simulated.
        rng: Shared random number generator; each call draws the next number
            from its continuous stream.

    Returns:
        True if a market order arrives and hits the quote during this time
        slice, False otherwise.
    """
    intensity = fill_intensity(delta, A, k)
    probability = intensity * dt
    rand = rng.random()

    return rand < probability
